export const descriptors: Record<string, string> = {
  a: 'Amazing',
  b: 'Amicable',
  c: 'Atrocious',
  d: 'Boisterous',
  e: 'Brazen',
  f: 'Breezy',
  g: 'Cool',
  h: 'Devious',
  i: 'Divine',
  j: 'Divisive',
  k: 'Electric',
  l: 'Energetic',
  m: 'Fresh',
  n: 'Gangly',
  o: 'Imaginative',
  p: 'Joyful',
  q: 'Kafkaesque',
  r: 'Litigious',
  s: 'Mellow',
  t: 'Morbid',
  u: 'Nifty',
  v: 'Nutritious',
  w: 'Obnoxious',
  x: 'Ordinary',
  y: 'Organic',
  z: 'Overrated',
  0: 'Peaceful',
  1: 'Poetic',
  2: 'Radical',
  3: 'Regal',
  4: 'Steady',
  5: 'Stinky',
  6: 'Subversive',
  7: 'Thoughtful',
  8: 'Treacherous',
  9: 'Tricky',
  a0: 'Uplifting',
  a1: 'Uplifting',
  a2: 'Wobbly',
  a3: 'Wonderful',
};

export const getDescriptorName = (key: string): string => {
  return descriptors[key] || key;
};
